name: food_shopping_app
description: A mobile application to make purchases of food items.

# The following defines the version and build number for your application.
# version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP package to make HTTP requests
  http: 1.2.1

  # Provider for state management
  provider: ^6.0.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
